:CmA: CommonAccord
:Cmorg: http://beta.commonaccord.org
:kv: key/value

:forteile: vorteile 

= Model Agt Frame


//graph
//table



[source,cypher]

----
CREATE (SpanF1:Span {title:'Agt._Body' ,value:'{Prologue}<ol><li>{Agt.Sec.S}</li></ol>{Agt.Signature}</br>{Agt.Attachment}'})

CREATE (SpanF2:Span {title:'Agt._Secs' ,value:'<ol><li>{Sec.Def}</li><li>{Sec.Deal}</li><li>{Sec.Term}</li><li>{Sec.Misc}</li></ol>'})
CREATE (SpanF2) -[:Extends]->(SpanF1)

CREATE (SpanF3:Span {title:'Misc._Sec' ,value:'<u>{Misc._Title}</u>. <ol><li>{Misc.Notice}</li><li>{Misc.Law}</li><li>{Misc.Forum}</li><li>{Misc.Entire}</li></ol>', extends:'Span2'})
CREATE (SpanF3) -[:Extends]->(SpanF2)

CREATE (SpanF4:Span {title:'Misc.Law._Sec' , value:'<u>Law</u>.  This agreement and any dispute relating to it shall be governed by the law of {Dispute.State.the}.'})
CREATE (SpanF4) -[:Extends]->(SpanF3)

CREATE (SpanF5:Span {title:'Prologue' , value:'{Pcpl.ID} and {Cttr.ID} hereby agree'})
CREATE (SpanF5) -[:Extends]->(SpanF4)


CREATE (SpanA1:Span {title:'(form)'})
CREATE (SpanA1) -[:UsesList]->(SpanF5)

CREATE (SpanA2:Span {title:'Pcpl.ID' , value:'Acme Inc., a Delaware corporation'})
CREATE (SpanA2) -[:Extends]->(SpanA1)


CREATE (SpanF6:Span {title:'Misc.Law._Sec' , value:'<u>Applicable Law</u>.  This Agreement and all disputes relating to it and the transactions contemplated by it are subject to {Dispute.State} law.'})
CREATE (SpanF6) -[:Extends]->(SpanF5)

CREATE (SpanA3:Span {title:'(form)'})
CREATE (SpanA3) -[:Extends]->(SpanA2)
CREATE (SpanA3) -[:UsesList]->(SpanF6)


WITH SpanA3
MATCH (k)<-[]-()
RETURN k.title as Key, k.value as Value
----


== Overview

The idea is to implement in a graph the list data model that is used in http://a.commonaccord.org/mediawiki/index.php/Main_Page
and deepened in some of the links referenced at http://beta.commonaccord.org.  

A list of key/values, where the value is either a span of html or the name of another list. 

A list can be understood as in Lisp - an item that prepends a shorter list, recursively.  That allows each bit of work to be separately recorded.  

== Notes

On reflection, the "UsesList" relationship notion seems incorrect.  The relationship creates a direct binding between  (SpanA3) -[]-> (SpanF6).  Instead of this kind of inline linking, it is better to use indirect linking.  So (SpanA3) would declare as a string the name or GUID of (SpanF6), and that would be resolved in an index. 
This would be consistent with how the keys for spans of text are resolved.  Needs a bit of thought. 

