:CmA: CommonAccord

:kv: key/value

:forteile: vorteile 

= Model Agt Frame


//graph
//table


[source,cypher]

----
CREATE (P1 {KV:'Name.First=James<>Name.Last=Hazard<>twitter=Hazardj'})
CREATE (List1)
CREATE (Span1 {span:'{Prologue}<ol><li>{Agt.Sec.S}</li></ol>{Agt.Signature}</br>{Agt.Attachment}'})
CREATE (Span2 {span:'<ol><li>{Sec.Def}</li><li>{Sec.Deal}</li><li>{Sec.Term}</li><li>{Sec.Misc}</li></ol>'})
CREATE (Span3 {span:'<u>{Misc.Title}</u>. <ol><li>{Misc.Notice}</li><li>{Misc.Law}</li><li>{Misc.Forum}</li><li>{Misc.Entire}</li></ol>'}) 
CREATE (Span4 {span:'<u>Law</u>.  This agreement and any dispute relating to it shall be governed by the law of {Dispute.State.the}.'})
CREATE (Span5 {span:'Miscellaneous'})

CREATE (List1) -[:LISTS {key:'Doc.Body'}]->(Span1)

CREATE (List1) -[:LISTS {key:'Agt.Sec.S'}]->(Span2)
CREATE (List1) -[:LISTS {key:'Sec.Misc'}]->(Span3)
CREATE (List1) -[:LISTS {key:'Sec.Law'}]->(Span4)
CREATE (List1) -[:LISTS {key:'Misc.Title'}]->(Span5)

CREATE (List2 {name:'MIT.edu/otl/NDA_Mutual'})
CREATE (Span2_1 {span:'<ol><li>{Sec.Conf}</li><li>{Sec.Use}</li><li>{Sec.Care}</li><li>{Sec.Compelled}</li><li>{Sec.Disclaim.Warranty}</li><li>{Sec.Term}</li><li>{Sec.Remedy}</li><li>{Sec.Notice}</li><li>{Sec.Misc}</li></ol>'} )
CREATE (List2) -[:LISTS {key:'Doc.Body'}]->(Span2_1)
CREATE (P1) -[:LIKES]->(List1)
CREATE (P1) -[:LIKES]->(List2)

CREATE (DS1 {href:'http://web.mit.edu/tlo/www/misc/forms.html'})
CREATE (DS1)<-[:HOSTED]-(List2)

WITH Span1
MATCH (v)<-[k:LISTS]-()
RETURN k.key, v.span
----


== This Approach (A1)

This is an extremely atomized approach to spans.  

== Another Approach (A2)

A different one would put all the {kv}s into a single node, either as (A2.1) a single string (value:'key1=value1<>key2=value2') or as (A2.2) individual attributes ( {key1='value1', key2='value2'}). 

== Analysis (so to speak)

There are front parts and back parts ({forteile} und nachteile) for both A1 and A2 solutions.  A2 is like beta.{cma}.org.   A2.2  has the disadvantage that there appears to be no Cypher search that returns the list of attributes.

* BTW The AsciiDoc native "attribute" function at gist.neo4j seems fussier than at github.  (F1) Error if the attribute is defined after the use.  (F2) spacing -  (F2.1) new line and (F2.2) space following second colon.

* (@hazardj)-[:SUGGEST {text: 'If an attribute could contain a call for another attribute and formating, we'd be mostly there.'}]->(@mojavelinux)

== Next Steps

Aggregate Lists and establish priority (recursive, depth-first) as among Spans with the same names.

@hazardj remembers how to do git coding locally instead of through github browser interface. 

